### PR TITLE
add entitlement to support iOS 14.

### PR DESCRIPTION
**Pull request by ghost**
To support iOS 14, you would need to add more entitlement.
Here's kernel log.
스크린샷 2021-02-06 오전 1 10 24

### CODE REVIEW

**Comment by ghost** [comment]
Confirmed it works on iOS 14.5b1

스크린샷 2021-02-06 오전 1 24 55

**Comment by yuruxuan** [comment]
Can you build a deb package to test on iOS 14?

**Comment by ManuSori** [comment]
Oh Wait! Crash fixed on iOS 14.3? :zany_face:

**Comment by iosTechnologies** [comment]
So is this working on ios 14 yet? Enabled it from Cydia and it does not connect. Anyone have an updated deb ?

**Comment by iosTechnologies** [comment]
> 
> 
> Confirmed it works on iOS 14.5b1
> 
> 스크린샷 2021-02-06 오전 1 24 55

Do you have to build it again from your updated build? Any chance someone can update this

**Comment by carmelsea** [comment]
@XsF1re Could you please release or upload an updated deb?
I tried to build it but encountered some errors.

Thank you.

**Comment by carmelsea** [comment]
@XsF1re 
Could you please release an updated deb based on your updates?
I tried to build it, but I encountered some errors.

Or maybe you could just upload your deb somewhere?

Thank you.

**Comment by rullinoiz** [comment]
> @XsF1re
> Could you please release an updated deb based on your updates?
> I tried to build it, but I encountered some errors.
> 
> Or maybe you could just upload your deb somewhere?
> 
> Thank you.

chances are i could build and test it and probably release something on my repo

**Review by Arengoh96 — CHANGES_REQUESTED** [review]
Request

**Review by Arengoh96 — APPROVED** [review]

**Review by Arengoh96 — APPROVED** [review]

**Comment by rullinoiz** [comment]
omg the madman did it

**Pull request merged**
